### ISSUE TITLE
ModuleNotFoundError: No module named 'data.data'

### ISSUE THREAD

**Issue by alirezaseifi** [lefnire/tforce_btc_trader#25]
I have the following issue by running the koggle.py script

```
Traceback (most recent call last):
  File "data/populate/kaggle.py", line 10, in <module>
    from data.data import engine
ModuleNotFoundError: No module named 'data.data'
```

**Comment by alirezaseifi** [comment]
Also getting this by running --test-live or --test not sure if it's related
```
  File "/tforce_btc_trader/env/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 507, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.ProgrammingError) relation "coinbase" does not exist
LINE 1: ...se.weighted_price as coinbase_weighted_price from coinbase o...
                                                             ^
 [SQL: 'select coinbase.open as coinbase_open, coinbase.high as coinbase_high, coinbase.low as coinbase_low, coinbase.close as coinbase_close, coinbase.volume_btc as coinbase_volume_btc, coinbase.volume_currency as coinbase_volume_currency, coinbase.weighted_price as coinbase_weighted_price from coinbase order by timestamp desc limit 100000 offset 0'] (Background on this error at: http://sqlalche.me/e/f405)

```

**Comment by alirezaseifi** [comment]
PYTHONPATH=. python data/populate/kaggle.py will resolve your issue
